### ISSUE TITLE
Task: Figure out how to build documentation via Sphinx

### ISSUE THREAD

**Issue by brianhhuynh38** [brianhhuynh38/slackpoint-v3#4]
The documentation for this project seems to be built with sphinx, located in the docs folder. We need to figure out how to compile and display any new documentation that we generate for our version of this project. When this is completed, please post instructions on how to compile the documentation, as well as describe the syntax associated with its generation.

**Comment by shinegami-2002** [comment]
I have successfully set up Sphinx documentation within the docs folder of our project, allowing us to compile and generate the latest documentation by navigating to the docs directory and running the make html command. Once compiled, the HTML files can be viewed locally in a web browser to verify updates before deployment. Additionally, our documentation is maintained and accessible through the GitHub Wiki.

<img width="1270" alt="image" src="https://github.com/user-attachments/assets/91c119eb-3ba3-4b2e-9529-b85967daa5e1">

**Comment by brianhhuynh38** [comment]
Alright, that looks pretty good. Nice job on getting the sphinx docs compiled. I'll go ahead and resolve this issue since we have guidance on how we can generate docs for the new implementation in the future.
