### ISSUE TITLE
Task: Design the method of gamification for the application extension

### ISSUE THREAD

**Issue by brianhhuynh38** [brianhhuynh38/slackpoint-v3#6]
This task is more related to the overall game design of the "deeper gamification" mentioned in [Iteration 2: Deeper Gamification](#2). The overall design of how the game should operate and what new parameters the new system will have to handle will have to be made.

If character stats are being added: 
- [x] What will these stats be?
- [x] What will they represent?
- [x] What role do they play in the overall scheme of things?
- [x] How do these stats affect each other and the game mechanics?
- [x] How might these be represented within the code as data?
- [x] How would a character be created with stats?

If a battle system is being considered: 
- [x] What interactions would be possible?
- [x] How would this be tracked in an application made primarily for text messaging?
- [x] How would a battle be represented in the data? How would this data be tracked?
- [x] How would this be initiated within the command system?

These are opening considerations to think about while coming up with the overall ideas and game mechanics. Initiate discussions below to identify and refine any mechanics that are being considered throughout the development of this project.

**Comment by brianhhuynh38** [comment]
# Character Stats and Stat Calculation Formulas

The following is a basic rundown and definition of a potential system that can be used to gamify the system. This section will deal with the character stats and formulas and will document the inner workings of each stat and each formula within the system.

## Character Stats

These stats split the different types of attacks into two different types of attacks: Magic and Physical. Strength and Defense primarily deal with physical attacks while Magic and Resistance represent the more ethereal aspects of the proposed battle system. Agility and Luck apply to both types of attacks, not in terms of damage, but in terms of the chance of the attack hitting.

| Stat | Description |
|-------------|--------------|
| **Strength (STR)** | The amount of strength a character has represents the amount of physical strength they have, and is applied to any physical-based move that may be in the game |
| **Magic (MAG)** | The amount of magic prowess a character has, is determinate of the amount of damage done by magic-based and non-physical attacks |
| **Defense (DEF)** | A value used to reduce the amount of damage done by physical attacks |
| **Resistance (RES)** | A value used to reduce the amount of damage done by magical attacks |
| **Agility (AGL)** | A value used to determine the hit rate and dodge rate of the character |
| **Luck (LUK)** | A value used to slightly influence the chance to hit and dodge on a small scale. Additionally, it should also factor into any RNG-based decisions that may occur during battle |

## Potential Calculation Formulas

The following are various calculations regarding the battle system, mostly dealing with damage calculation and hit rate generation:

### Proposed Damage Calculation Formulas

The following are potential damage calculation functions for both physical and magical damage. They essentially perform the same calculation, but with their respective physical and magical values. Each calculation also uses a random factor in which it introduces a variation in possible damage outputs from a multiplier of 1.0 to 1.1. The higher the user's Luck, the higher chance they will have to roll a higher multiplier.

The damage calculation formula uses a variation of a common multiplicative damage formula that is used in a lot of games, such as _SMITE_. Defense and Resistance serve as ways to dampen the amount of damage done to the player. This allows for higher damage and HP values when compared to simpler subtractive implementations where the attack is subtracted by defense to get the difference between them.

$$
Physical \ Damage: DMG = Random(1.0f + (LUK / 100), 1.1f) * (\frac{(Base Power + STR)^2}{(Base Power + STR) - DEF})
$$

$$
Magical \ Damage: DMG = Random(1.0f + (LUK / 100), 1.1f) * (\frac{(Base Power + MAG)^2}{(Base Power + MAG) - RES})
$$

**Comment by brianhhuynh38** [comment]
I am going to move this into a GitHub Wiki page for now since it's probably crowding the discussion for this issue. From now on, please reference the page in the GitHub Wiki for review of the design proposals. Please let me know if anyone has any additional comments on the overall design.

**Comment by shinegami-2002** [comment]
The Character Stats and Stat Calculation Formulas documentation is comprehensive and detailed. Great work on putting this together and keeping the GitHub wiki up-to-date. I'll close this issue.
